# Generated by Django 4.0.1 on 2022-01-13 01:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summerizer_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Feeback',
            new_name='Feedback',
        ),
    ]
