# Generated by Django 4.0.1 on 2022-01-15 12:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerizer_app', '0002_rename_feeback_feedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='msg',
            field=models.CharField(default='', max_length=255),
        ),
    ]
