# Generated by Django 4.0.1 on 2022-01-15 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('summerizer_app', '0003_feedback_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='feedback',
            name='email',
            field=models.CharField(default='', max_length=255),
        ),
    ]
