# Generated by Django 4.0.1 on 2022-01-16 18:02

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('summerizer_app', '0004_feedback_email'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback_percent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('good_percent', models.FloatField()),
                ('bad_percent', models.FloatField()),
            ],
        ),
    ]
